server:
  port: 8001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alittlesmile/alittlebit.git    # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: alittlesmile                                             # git仓库的账号
          password: junqiang0531                                            # git仓库的密码